# 사용 플랫폼
language : android
# jdk 버전
jdk : oraclejdk8
# 플랫폼 컴포넌트 ->  travis가 소스를 컴파일하고 에뮬레이터에서 돌리기위한 모든 도구들
# 즉 트래비스가 이 도구들을 다운받아서 사용한다.
android:
  components:
  - platform-tools   #  ADB - 에뮬레이터, 디바이스와 통신을 하는 모듈
  - tools   #   안드로이드 sdk
  - build-tools-24.0.0  # 빌드하는 툴
  - android-23  # 타겟 안드로이드 플랫폼
  - extra-android-m2repository # 의존성 라이브러리를 관리하는 툴

# 스크립트 실행전 명령어
before_install:
  - chmod +x gradlew            # chmod 개별 사용자 권한 변경

# 스크립트 명령어
script: ./gradlew build
